server:
  port: 8080

spring:
  application:
    name: sale-system
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sale?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: xxxxxx # Back to original
  sql:
    init:
      mode: never # Persist data
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # For debugging SQL
